lib: [
  "_build/install/default/lib/SimplePpx/META"
  "_build/install/default/lib/SimplePpx/dune-package"
  "_build/install/default/lib/SimplePpx/lib/Ppx.re" {"lib/Ppx.re"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.a" {"lib/ppx_deriving_accessors.a"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.cma" {"lib/ppx_deriving_accessors.cma"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.cmi" {"lib/ppx_deriving_accessors.cmi"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.cmt" {"lib/ppx_deriving_accessors.cmt"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.cmx" {"lib/ppx_deriving_accessors.cmx"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.cmxa" {"lib/ppx_deriving_accessors.cmxa"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.cmxs" {"lib/ppx_deriving_accessors.cmxs"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors.ml" {"lib/ppx_deriving_accessors.ml"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors__Ppx.cmi" {"lib/ppx_deriving_accessors__Ppx.cmi"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors__Ppx.cmt" {"lib/ppx_deriving_accessors__Ppx.cmt"}
  "_build/install/default/lib/SimplePpx/lib/ppx_deriving_accessors__Ppx.cmx" {"lib/ppx_deriving_accessors__Ppx.cmx"}
  "_build/install/default/lib/SimplePpx/opam"
]
bin: [
  "_build/install/default/bin/ManualTest"
  "_build/install/default/bin/simple-ppx"
]
doc: [
  "_build/install/default/doc/SimplePpx/LICENSE"
  "_build/install/default/doc/SimplePpx/README.md"
]
